name: Daily Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with email 23f1003086@ds.study.iitm.ac.in
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          
      - name: Create update file
        run: echo "Automated update: $(date -u)" > update.log
        
      - name: Configure Git and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "23f1003086@ds.study.iitm.ac.in"
          git add update.log
          git commit -m "Daily automated commit - $(date -u)"
          git push
